import {
  type LucideIcon,
  Facebook,
  Youtube,
  Instagram,
  PinIcon as Pinterest,
  Linkedin,
  SnailIcon as Snapchat,
  RssIcon as Reddit,
  PhoneIcon as Whatsapp,
  TextIcon as Telegram,
  DiscIcon as Discord,
  AirplayIcon as Spotify,
  Twitch,
  VideoIcon as Vimeo,
  Slack,
  WebcamIcon as Skype,
  TwitterIcon as Tumblr,
  GalleryThumbnailsIcon as Flickr,
  CloudIcon as Soundcloud,
  DribbbleIcon as Behance,
  Dribbble,
  Github,
  Codepen,
  SunMediumIcon as Medium,
  QrCodeIcon as Quora,
  VibrateIcon as Viber,
  PenLineIcon as Line,
  TwitterIcon as Weibo,
  PhoneIcon as Wechat,
  InstagramIcon as Tiktok,
  X,
  GavelIcon as Giphy,
} from "lucide-react"

export const allSocialPlatforms = [
  {
    icon: Facebook,
    name: "Facebook",
    displayName: "Facebook",
    color: "from-blue-600 to-blue-700",
    textColor: "text-blue-600",
  },
  {
    icon: Youtube,
    name: "Youtube",
    displayName: "Youtube",
    color: "from-red-600 to-red-700",
    textColor: "text-red-600",
  },
  {
    icon: Instagram,
    name: "Instagram",
    displayName: "Instagram",
    color: "from-pink-500 to-purple-600",
    textColor: "text-pink-500",
  },
  {
    icon: X,
    name: "X",
    displayName: "Twitter",
    color: "from-gray-800 to-black",
    textColor: "text-black dark:text-white",
  },
  {
    icon: Tiktok,
    name: "Tiktok",
    displayName: "Tiktok",
    color: "from-black to-gray-800",
    textColor: "text-black dark:text-white",
  },
  {
    icon: Giphy, // Placeholder for Giphy
    name: "Giphy",
    displayName: "Giphy",
    color: "from-green-500 to-teal-600",
    textColor: "text-green-500",
  },
  {
    icon: Pinterest,
    name: "Pinterest",
    displayName: "Pinterest",
    color: "from-red-500 to-red-600",
    textColor: "text-red-500",
  },
  {
    icon: Linkedin,
    name: "Linkedin",
    displayName: "LinkedIn",
    color: "from-blue-700 to-blue-800",
    textColor: "text-blue-700",
  },
  {
    icon: Snapchat,
    name: "Snapchat",
    displayName: "Snapchat",
    color: "from-yellow-400 to-yellow-500",
    textColor: "text-yellow-400",
  },
  {
    icon: Reddit,
    name: "Reddit",
    displayName: "Reddit",
    color: "from-orange-600 to-orange-700",
    textColor: "text-orange-600",
  },
  {
    icon: Whatsapp,
    name: "Whatsapp",
    displayName: "WhatsApp",
    color: "from-green-600 to-green-700",
    textColor: "text-green-600",
  },
  {
    icon: Telegram,
    name: "Telegram",
    displayName: "Telegram",
    color: "from-blue-500 to-blue-600",
    textColor: "text-blue-500",
  },
  {
    icon: Discord,
    name: "Discord",
    displayName: "Discord",
    color: "from-indigo-600 to-indigo-700",
    textColor: "text-indigo-600",
  },
  {
    icon: Spotify,
    name: "Spotify",
    displayName: "Spotify",
    color: "from-green-500 to-green-600",
    textColor: "text-green-500",
  },
  {
    icon: Twitch,
    name: "Twitch",
    displayName: "Twitch",
    color: "from-purple-600 to-purple-700",
    textColor: "text-purple-600",
  },
  {
    icon: Vimeo,
    name: "Vimeo",
    displayName: "Vimeo",
    color: "from-blue-600 to-blue-700",
    textColor: "text-blue-600",
  },
  {
    icon: Slack,
    name: "Slack",
    displayName: "Slack",
    color: "from-purple-600 to-pink-600",
    textColor: "text-purple-600",
  },
  {
    icon: Skype,
    name: "Skype",
    displayName: "Skype",
    color: "from-blue-500 to-blue-600",
    textColor: "text-blue-500",
  },
  {
    icon: Tumblr,
    name: "Tumblr",
    displayName: "Tumblr",
    color: "from-blue-800 to-indigo-900",
    textColor: "text-blue-800",
  },
  {
    icon: Flickr,
    name: "Flickr",
    displayName: "Flickr",
    color: "from-pink-600 to-purple-700",
    textColor: "text-pink-600",
  },
  {
    icon: Soundcloud, // Placeholder for Soundcloud
    name: "Soundcloud",
    displayName: "SoundCloud",
    color: "from-orange-500 to-orange-600",
    textColor: "text-orange-500",
  },
  {
    icon: Behance,
    name: "Behance",
    displayName: "Behance",
    color: "from-blue-600 to-blue-700",
    textColor: "text-blue-600",
  },
  {
    icon: Dribbble,
    name: "Dribbble",
    displayName: "Dribbble",
    color: "from-pink-600 to-pink-700",
    textColor: "text-pink-600",
  },
  {
    icon: Github,
    name: "Github",
    displayName: "GitHub",
    color: "from-gray-800 to-gray-900",
    textColor: "text-gray-800 dark:text-gray-300",
  },
  {
    icon: Codepen,
    name: "Codepen",
    displayName: "CodePen",
    color: "from-gray-800 to-black",
    textColor: "text-gray-800 dark:text-gray-300",
  },
  {
    icon: Medium,
    name: "Medium",
    displayName: "Medium",
    color: "from-gray-800 to-gray-900",
    textColor: "text-gray-800 dark:text-gray-300",
  },
  {
    icon: Quora,
    name: "Quora",
    displayName: "Quora",
    color: "from-red-600 to-red-700",
    textColor: "text-red-600",
  },
  {
    icon: Viber, // Placeholder for Viber
    name: "Viber",
    displayName: "Viber",
    color: "from-purple-600 to-purple-700",
    textColor: "text-purple-600",
  },
  {
    icon: Line, // Placeholder for Line
    name: "Line",
    displayName: "Line",
    color: "from-green-500 to-green-600",
    textColor: "text-green-500",
  },
  {
    icon: Weibo, // Placeholder for Weibo
    name: "Weibo",
    displayName: "Weibo",
    color: "from-red-600 to-red-700",
    textColor: "text-red-600",
  },
  {
    icon: Wechat,
    name: "Wechat",
    displayName: "WeChat",
    color: "from-green-600 to-green-700",
    textColor: "text-green-600",
  },
]

export const iconComponentsMap = allSocialPlatforms.reduce(
  (acc, platform) => {
    acc[platform.name] = platform.icon
    return acc
  },
  {} as Record<string, LucideIcon>, // Add type assertion here
)

export const availableIconOptions = allSocialPlatforms.map((platform) => ({
  name: platform.name,
  displayName: platform.displayName,
}))
